name: Build Android Project for PR

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-android:
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.51

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Build Android only
        run: dotnet build ./10.0/Apps/PointOfSale/PointOfSale.csproj -f net10.0-android
