name: Build Project for PR

on:
  pull_request:
    branches: [ main ]

jobs:
   build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - name: Restore workloads
        run: dotnet workload restore

      - name: Install MAUI workloads
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore ./10.0/Apps/PointOfSale/src/PointOfSale/PointOfSale.csproj

      - name: Build Android
        run: dotnet build ./10.0/Apps/PointOfSale/src/PointOfSale/PointOfSale.csproj -f net10.0-android --configuration Release --no-restore
        
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ./10.0/Apps/PointOfSale/src/PointOfSale/PointOfSale.csproj
      - name: Build
        run: dotnet build ./10.0/Apps/PointOfSale/src/PointOfSale/PointOfSale.csproj --configuration Release --no-restore

  build-macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ./10.0/Apps/PointOfSale/src/PointOfSale/PointOfSale.csproj
      - name: Build
        run: dotnet build ./10.0/Apps/PointOfSale/src/PointOfSale/PointOfSale.csproj --configuration Release --no-restore
